{
 "title": "JSON RPC Relay (Official)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Usage - Hbar Account and Burn Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Relay Operator Balance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(accountId)  (rpc_relay_operator_balance{cluster=\"$cluster\", namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"} / 100000000)",
     "legendFormat": "Account: {{accountId}}"
    }
   ]
  },
  {
   "title": "Operator account burn rate (ℏ)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) / -100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Relay Operator Balance (ℏ)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(rpc_relay_operator_balance{cluster=\"$cluster\", namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[$__interval]) / 100000000",
     "legendFormat": "{{accountId}}"
    }
   ]
  },
  {
   "title": "Operator Cost  (ℏ) by Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) / -100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Consensus Node (txns) Calls by Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Consensus Node Cost Rate by Call (ℏ)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "sum by(caller) (rate(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) / 100000000",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Consensus Node Cost by Call (ℏ)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) / 100000000)",
     "legendFormat": " {{caller}}"
    }
   ]
  },
  {
   "title": "Consensus Node Volume by Call ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])))",
     "legendFormat": " {{caller}}"
    }
   ]
  },
  {
   "title": "Hbar Spent By type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[1d])) by(type) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent By Mode",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by(mode) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent By caller",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by(caller) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month By Mode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[1d])) by(mode) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last day By Mode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[30m])) by(mode) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod) / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month by MethodName",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[1d])) by(caller) / 100000000",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[1d])) by(type) / 100000000",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Consensus Node Calls by AccountId/EvmAddress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_count{cluster=\"$cluster\",namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])))",
     "legendFormat": "{{interactingEntity}}"
    }
   ]
  },
  {
   "title": "Hbar Spent by AccountId/EvmAddress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_sum{cluster=\"$cluster\",namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])) / 100000000)",
     "legendFormat": "{{interactingEntity}}"
    }
   ]
  },
  {
   "title": "Volume, RPS, Latency, Limits - API Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }
  },
  {
   "title": "Request Rate (RPS)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 3, "y": 90 },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Request Rate (RPS)"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 3, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_bucket{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\"}[$__rate_interval]))",
     "legendFormat": "Failed Request RPS"
    }
   ]
  },
  {
   "title": "Failure %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\"}[$__range]))/sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Total Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth_call Failure Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_call\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth_call Failed Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 4, "y": 100 },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_bucket{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_call\"}[$__rate_interval]))",
     "legendFormat": "Failed Request RPS"
    }
   ]
  },
  {
   "title": "eth_call Failure %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_call\"}[$__range]))/sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth_call Failure Total Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_call\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth_sendRawTransaction Failure Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth_sendRawTransaction Failed Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 4, "y": 105 },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_bucket{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_sendRawTransaction\"}[$__rate_interval]))",
     "legendFormat": "Failed Request RPS"
    }
   ]
  },
  {
   "title": "eth_sendRawTransaction Failure %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_sendRawTransaction\"}[$__range]))/sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eth_sendRawTransaction Failure Total Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Requests by Path (units)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum by(method)(increase(rpc_relay_method_response_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Amount of Requests by Path (units)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum by(method)(increase(rpc_relay_method_response_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Requests by Path (units)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "topk(15,sum by(method)(increase(rpc_relay_method_response_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Requests by Path (units) - Per day over the month",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "topk(15,sum by(method)(increase(rpc_relay_method_response_count{cluster=\"$cluster\",namespace=\"$namespace\"}[1d])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Requests to API by MethodName",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method)(increase(rpc_relay_method_response_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failed Requests to API by MethodName",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 150 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method)(increase(rpc_relay_method_response_count{cluster=\"$cluster\",namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code (excluding 200)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum by(statusCode)(increase(rpc_relay_method_response_count{cluster=\"hashio-external\",namespace=\"testnet\",statusCode!=\"200\"}[$__range]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Avg. Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 169 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(rpc_relay_method_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) / avg (rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Relay"
    },
    {
     "expr": "avg(rate(rpc_relay_mirror_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))/avg(rate(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Mirror Node"
    }
   ]
  },
  {
   "title": "Avg. Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 169 },
   "targets": [
    {
     "expr": "avg (rate(rpc_relay_method_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) / avg (rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Relay E2E Avg. Latency"
    },
    {
     "expr": "avg(rate(rpc_relay_mirror_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))/avg(rate(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Mirror Node Avg. Latency"
    }
   ]
  },
  {
   "title": "Response Latency (ms) by Path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "sum by (method) (rate(rpc_relay_method_response_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) / sum by (method) (rate(rpc_relay_method_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mirror Node Calls by Method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "sum by(method)(increase(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Node Calls by StatusCode (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 197 },
   "targets": [
    {
     "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Node Contract/Call Calls by StatusCode (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 207 },
   "targets": [
    {
     "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Node Contract/Call Calls by StatusCode (Units)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 217 },
   "targets": [
    {
     "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Node Contract/Call Calls by StatusCode (%)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 217 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\", method=\"contracts/call\"}[$__range]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Node RPS by Path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_mirror_response_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Node Latency by Path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_mirror_response_sum{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (method) /\nsum(rate(rpc_relay_mirror_response_count{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Mirror Response by Status & Type (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 248 },
   "targets": [
    {
     "expr": "topk by(statusCode) (5, sum by(statusCode, method) (rate(rpc_relay_mirror_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "[{{statusCode}}] {{method}}"
    }
   ]
  },
  {
   "title": "Consensus Node Calls by Status (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 258 },
   "targets": [
    {
     "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Transaction Response by Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 268 },
   "targets": [
    {
     "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{cluster=\"$cluster\", namespace=\"$namespace\", mode=\"TRANSACTION\", type=\"EthereumTransaction\"}[$__rate_interval])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Query Response by Status & Type (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 278 },
   "targets": [
    {
     "expr": "topk by(status) (10, sum by(status, type) (rate(rpc_relay_consensusnode_response_count{cluster=\"$cluster\", namespace=\"$namespace\", mode=\"QUERY\"}[$__rate_interval])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "IP Rate Limiter by Method",
   "type": "barchart",
   "description": "Amount of times the IP Rate Limited has limited a request by method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "targets": [
    {
     "expr": "sum by(methodName)(rpc_relay_ip_rate_limit{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Hbar Rate Limiter by Method",
   "type": "barchart",
   "description": "Amount of times the Hbar Rate Limited has limited a request grouped by method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_hbar_rate_limit{cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 296 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Node.js memory",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 297 },
   "targets": [
    {
     "expr": "avg(rpc_relay_nodejs_external_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "External"
    },
    {
     "expr": "avg(rpc_relay_process_resident_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Resident"
    },
    {
     "expr": "avg(rpc_relay_nodejs_heap_size_used_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "avg(rpc_relay_nodejs_heap_size_total_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Heap Total"
    }
   ]
  },
  {
   "title": "Current Avg. CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(rpc_relay_process_cpu_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 305 },
   "targets": [
    {
     "expr": "avg(rate(rpc_relay_process_cpu_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))*100",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(rate(rpc_relay_process_cpu_system_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))*100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(rpc_relay_process_cpu_user_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))*100",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 313 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{cluster=\"$cluster\",namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 321 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Pod Socket count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 329 },
   "targets": [
    {
     "expr": "container_sockets{cluster=\"$cluster\",namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}